# Determines the number of threads each step uses
# Adjust to fit the needs of your system
set-threads:
  align_aa: 4
  realign_outliers_before_trimal: 4
  realign_outliers_after_trimal: 4

# Determines rule specific resources (primarily
# runtime, but also memory if needed). These
# runtimes are maximums for submitted jobs, so
# they should be high for the longest running
set-resources:
  align_aa:
    runtime: "3d"
  realign_outliers_before_trimal:
    runtime: "3d"
  realign_outliers_after_trimal:
    runtime: "3d"
  infer_gene_trees_before_trimal:
    runtime: "3d"
  infer_gene_trees_after_trimal:
    runtime: "3d"
  final_gene_trees:
    runtime: "3d"
