# Determines the number of threads each step uses
# Adjust to fit the needs of your system
set-threads:
  align_aa: 2
  infer_gene_trees_before_trimal_iqtree: 4
  infer_gene_trees_before_trimal_fasttree: 1
  realign_outliers_before_trimal: 2
  infer_gene_trees_after_trimal_iqtree: 4
  infer_gene_trees_after_trimal_fasttree: 1
  realign_outliers_after_trimal: 2
  final_gene_trees: 4

# Put jobs in group to avoid short running slurm jobs
groups:
  - init_before_trimal=first_pass
  - align_aa=first_pass
  - backtranslate=first_pass
  - clean_all_gap_seqs=first_pass
  - infer_gene_trees_before_trimal_iqtree=first_pass
  - infer_gene_trees_before_trimal_fasttree=first_pass
  - unalign_outliers_before_trimal=second_pass
  - realign_outliers_before_trimal=second_pass
  - run_trimal=second_pass
  - init_after_trimal=second_pass
  - infer_gene_trees_after_trimal_iqtree=second_pass
  - infer_gene_trees_after_trimal_fasttree=second_pass
  - unalign_outliers_after_trimal=third_pass
  - realign_outliers_after_trimal=third_pass
  - backtranslate_final=third_pass

# Determines rule specific resources (primarily
# runtime, but also memory if needed). These
# runtimes are maximums for submitted jobs, so
# they should be high for the longest running
set-resources:
  align_aa:
    runtime: "3h"
  realign_outliers_before_trimal:
    runtime: "3h"
  realign_outliers_after_trimal:
    runtime: "3h"
  infer_gene_trees_before_trimal_iqtree:
    runtime: "55h"
  infer_gene_trees_after_trimal_iqtree:
    runtime: "55h"
  infer_gene_trees_before_trimal_fasttree:
    runtime: "55h"
  infer_gene_trees_after_trimal_fasttree:
    runtime: "55h"
  final_gene_trees:
    runtime: "3d"
