### Software paramaters

gene_table: gene_table.tsv
params:
    general:
        maxgap_pct: 0.95
    align_aa:
      aligner: "fftns" ##harcode an alignment algo, or set it to "auto"
      auto_criterion: "filesize" ##"filesize" or "mafft", in the latter case we run "mafft --auto"
      large_gene_threshold_mb: 10 ##genes with filesize larger than this will use the 'large_gene_aligner'. The current and the next 2 lines are applicable only when aligner: "auto" and auto_criterion: "filesize"
      small_gene_aligner: "linsi"
      large_gene_aligner: "fftns"
      mafft_tmpdir: "" ## Here you can provide a directory you create as the base-level alignment tmpdir. Leave empty unless you are facing TMPDIR related problems.
    concatenate:
        min_aln_len: 0
    detect_outliers:
        taxa_threshold: 0.7
        long_branch_threshold: 0.08
        treeshrink_mode: "auto"
    final_gene_trees:
        model: "MFP"
        branch_support_args: "-B 1000 -alrt 1000 -bnni"
