restart-times: 0 # if jobs fail they restart this many times
cores: 46 # set this the the number of cores you are willing to run analyses on
printshellcmds: true
sdm: "conda apptainer" # change to just conda if you are not using apptainer/singularity
keep-going: true
apptainer-args: "" # add any special arguments for apptainer/singularity that you need to have on your system to run containers
default-resources:
  - "mem_mb=(threads*5300)" # set to how many MB per core you have available on your system
  - "runtime=60m"
