restart-times: 0 # how many retries to give a step if it fails
local-cores: 2 # how many cores to let the snakemake command use outside of jobs (for fast steps like file linking)
printshellcmds: true
sdm: "conda apptainer" # change to just conda if you are not using apptainer/singularity
jobs: 999 # how many jobs to submitted/running in the SLURM queue at once
keep-going: true
max-threads: 40 # maximum threads/cpus available on the nodes you submit to (40 if partition==small on CSC)
max-jobs-per-second: 1 # submit only 1 job per second to not overwhelm the queue
max-status-checks-per-second: 1
executor: "slurm"
default-resources:
  - "mem_mb=(threads*9200)" # Small partition has about 382000 MB memory X 40 cpus, so we can give up to 9500 MB per cpu
  - "runtime=60m" # leave as is, the rules will ask for more if they need them (up to the value specified per rule in profiles/default/config.yaml)
  - "slurm_account=account" # replace with your slurm account (i.e. #SBATCH -A/--account)
  - "slurm_partition=small" # replace with your slurm partition to submit to (i.e. #SBATCH -p/--partition),
# If you need to pass more info the the sbatch commands, see https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html#slurm-specific-resources for more options
